### ISSUE TITLE
Please provide a way to build without vendored liburing

### ISSUE THREAD

**Issue by glondu** [ocaml-multicore/ocaml-uring#156]
This package vendors liburing. I don't understand why this is necessary. Please explain and/or provide a way to build with system liburing.

**Comment by avsm** [comment]
It's necessary since we test against a specific version of liburing. I'm not overly keen on having a potentially different version in use, since the Linux kernel ABI is the only stable interface here...

**Comment by avsm** [comment]
I do note, though, that Debian currently has the same version of liburing in unstable, so this would work in the short term if you're looking to package up ocaml-uring there (which is, I assume, the background reason for creating this issue)

**Comment by glondu** [comment]
> [...] since the Linux kernel ABI is the only stable interface here...

liburing has a soname. This provides some sort of stability. What you say is true for any library, you wouldn't vendor any library in its bindings... I don't understand why liburing is special here.

> Debian [...] is, I assume, the background reason for creating this issue

Indeed. Patches applied in the Debian package are available there: https://salsa.debian.org/ocaml-team/ocaml-uring/-/tree/master/debian/patches

Do note that, for now, I packaged ocaml-uring 2.7.0 and it seems to work with the sid version of liburing (2.14).

**Comment by talex5** [comment]
> This package vendors liburing. I don't understand why this is necessary.

uring is often installed via opam and often requires a newer version of liburing than the host distribution provides. For example, with your changes, the current (Git) version of uring fails to install on Debian 13:

```
$ dune build
File "lib/uring/dune", line 8, characters 9-20:
8 |   (names uring_stubs)
             ^^^^^^^^^^^
uring_stubs.c: In function 'ocaml_uring_submit_readv_fixed':
uring_stubs.c:406:3: error: implicit declaration of function 'io_uring_prep_readv_fixed'; did you mean 'io_uring_prep_read_fixed'? [-Wimplicit-function-declaration]
  406 |   io_uring_prep_readv_fixed(sqe, Int_val(v_fd), iovs, len, Int63_val(v_fileoff), 0, 0);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
      |   io_uring_prep_read_fixed
...
```

For packaging uring itself in Debian I agree it makes sense to use Debian's liburing. I'm not sure if there's an easier way of doing it than just patching it out as you're doing already. Do you have a suggestion on how to do it?

**Comment by glondu** [comment]
> the current (Git) version of uring fails to install on Debian 13

So you're saying ocaml-uring depends on a minimum version of liburing that is not available on Debian 13. This kind of pattern happens all the time, and is not good justification for vendoring libFOO into ocaml-FOO. Just declare the minimum required version of libFOO (too bad if the host distribution does not provide it, someone who cares will make it available), but please don't vendor it.

> For packaging uring itself in Debian I agree it makes sense to use Debian's liburing. I'm not sure if there's an easier way of doing it than just patching it out as you're doing already. Do you have a suggestion on how to do it?

Maybe: check the version of the system liburing, and if it does not meet the requirements, fail early. Or download a proper version. But you are reinventing a package manager.

With you reasoning pushed to the extreme, one would vendor all dependencies (unfortunately, this is an established recurring pattern).

**Comment by avsm** [comment]
There's no point pushing our reasoning to the extreme, as we're not [rebuilding a package manager](https://arxiv.org/abs/2602.18602) nor are we setting a precedent for this beyond this specific C library (which is tightly coupled with both a kernel ABI and these bindings). The current vendoring model is pretty important for opam distribution since liburing isn't widely available yet on several Linux distros.

I am of course sympathetic to the Debian case, so I took a look at decoupling the vendoring as an optional environmental variable. It does get a bit messy unfortunately, but I'll take a look again for a future version. For now, I agree with @talex5 that maintaining a patch at the packaging layer may be best.

**Comment by avsm** [comment]
@glondu, I'm not ignoring this; I am struggling to figure out the build runes to make this work when both vendored and not vendored!

**Comment by ifreund** [comment]
I ended up here due to the vendored copy of liburing failing to build on the (admittedly niche) Linux distro I use (https://chimera-linux.org).

It would be great to see a option to disable vendoring, not only to make Debian packagers happier but to improve portability!

Edit: setting `CC=/usr/bin/clang` was actually sufficient for the vendored version to build for me.
