### ISSUE TITLE
Fails to build with musl 1.2.5

### ISSUE THREAD

**Issue by alyssais** [ocaml-multicore/ocaml-uring#112]
musl 1.2.5 newly provides some statx support in <sys/stat.h>, but it does not define the `STATX_ATTR_*` constants, causing this build failure:

```
run: gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC  -D_GNU_SOURCE -I /build/uring-0.8/_build/default/lib/uring/include -I /nix/store/yspc3sc7nkgspq2l0larmf46flhk1r4n-ocaml-5.0.0/lib/ocaml -o /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.o -c /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c -lm -lpthread
-> process exited with code 1
-> stdout:
-> stderr:
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:198:14: error: ‘STATX_ATTR_COMPRESSED’ undeclared here (not in a function)
 |   198 |   DUNE_SIGN((STATX_ATTR_COMPRESSED)),
 |       |              ^~~~~~~~~~~~~~~~~~~~~
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:33:24: note: in definition of macro ‘DUNE_SIGN’
 |    33 | #define DUNE_SIGN(x) ((x >= 0)? '0': '-')
 |       |                        ^
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:206:14: error: ‘STATX_ATTR_IMMUTABLE’ undeclared here (not in a function)
 |   206 |   DUNE_SIGN((STATX_ATTR_IMMUTABLE)),
 |       |              ^~~~~~~~~~~~~~~~~~~~
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:33:24: note: in definition of macro ‘DUNE_SIGN’
 |    33 | #define DUNE_SIGN(x) ((x >= 0)? '0': '-')
 |       |                        ^
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:214:14: error: ‘STATX_ATTR_APPEND’ undeclared here (not in a function)
 |   214 |   DUNE_SIGN((STATX_ATTR_APPEND)),
 |       |              ^~~~~~~~~~~~~~~~~
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:33:24: note: in definition of macro ‘DUNE_SIGN’
 |    33 | #define DUNE_SIGN(x) ((x >= 0)? '0': '-')
 |       |                        ^
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:222:14: error: ‘STATX_ATTR_NODUMP’ undeclared here (not in a function); did you mean ‘STATX_ATTR_DAX’?
 |   222 |   DUNE_SIGN((STATX_ATTR_NODUMP)),
 |       |              ^~~~~~~~~~~~~~~~~
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:33:24: note: in definition of macro ‘DUNE_SIGN’
 |    33 | #define DUNE_SIGN(x) ((x >= 0)? '0': '-')
 |       |                        ^
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:230:14: error: ‘STATX_ATTR_ENCRYPTED’ undeclared here (not in a function); did you mean ‘STATX_ATTR_VERITY’?
 |   230 |   DUNE_SIGN((STATX_ATTR_ENCRYPTED)),
 |       |              ^~~~~~~~~~~~~~~~~~~~
 | /build/build_458c2a_dune/ocaml-configurator434ca2/c-test-4/test.c:33:24: note: in definition of macro ‘DUNE_SIGN’
 |    33 | #define DUNE_SIGN(x) ((x >= 0)? '0': '-')
 |       |                        ^
Error: failed to compile program
```

It's not possible to just include <linux/stat.h> afterwards, if some constants are missing from <sys/stat.h>, because then there will be type redefinition errors for e.g. `struct statx`.

**Comment by richfelker** [comment]
I think these were just an omission we should fix on the musl side, but in general applications should probably only use STATX macros after checking their presence with `#ifdef`.

**Comment by talex5** [comment]
Was this compiling before on musl? It looks like it already required these constants to be defined.

There's already some support for missing flags, but it just defines them to 0 if unknown, which doesn't seem right. I think we should add all the flags to `new_flags` and provide the correct value if unknown:

https://github.com/ocaml-multicore/ocaml-uring/blob/07db8c0202e362292d4378da7c3396bc91dbd8f9/lib/uring/include/discover.ml#L113-L129

**Comment by alyssais** [comment]
> Was this compiling before on musl? It looks like it already required these constants to be defined.

It was, because previously musl's <sys/stat.h> did not define STATX_TYPE, so it would get them from <linux/stat.h>:

https://github.com/ocaml-multicore/ocaml-uring/blob/07db8c0202e362292d4378da7c3396bc91dbd8f9/lib/uring/include/discover.ml#L132-L135

**Comment by alyssais** [comment]
https://github.com/ocaml-multicore/ocaml-uring/pull/114
